my.greeting: hello

app:
    name: My App
    description: Welcome to ${app.name}

my.list.values: one,two,three

dbValues: "{connectionString: 'http://____', username: 'foo', password: 'pass'}"

db:
   connection: "{connectionString: 'http://____', username: 'foo', password: 'pass'}"
   host: 127.0.0.1
   port: 3306

# expose everyting
management:
     endpoints:
         web:
           exposure:
             include: "*"

spring:
     profiles:
         active: test
